version: '2.1'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    container_name: "sql-db"
    ports:
      - 3306:3306

  app:
    build: .
    container_name: "hibernate-starter"
    depends_on:
      - db